name: Deploy to GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out...
      uses: actions/checkout@v2
    - name: Setting up Node.js...
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - name: Installing dependencies...
      run: npm ci
    - name: Building...
      run: npm run build
    - name: Deploying...
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: master
