name: Run tests

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out...
      uses: actions/checkout@v2
    - name: Setting up Node.js...
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - name: Installing dependencies...
      run: npm ci
    - name: Testing...
      run: npm run test
